services:
  app:
    build: .
    container_name: quotes_app_prod
    env_file:
      - .env.prod
    environment:
      - DJANGO_SETTINGS_MODULE=config.settings_production.py
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    expose:
      - "8000"

  nginx:
    image: nginx:1.25-alpine
    container_name: quotes_nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/media:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

volumes:
  static_volume:
  media_volume:
